export const PATHS = {
  COMMON: '/',
  COMMENTS: '/comments',
  BLOGS: '/blogs',
  POSTS: '/posts',
  USERS: '/users',
  TESTING: '/testing',
  SECURITY: '/security',
  AUTH: {
    COMMON: '/auth',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REGISTRATION: '/auth/registration',
    CONFIRM_REGISTRATION: '/auth/registration-confirmation',
    REGISTRATION_EMAIL_RESENDING: '/auth/registration-email-resending',
    REFRESH_TOKEN: '/auth/refresh-token',
    PASSWORD_RECOVERY: '/auth/password-recovery',
    NEW_PASSWORD: '/auth/new-password',
    ME: '/auth/me',
  },
};
